### ISSUE TITLE
Can you provide some relevant datasets

### ISSUE THREAD

**Issue by hyybuaa** [kaharjan/UyNeRel#2]
we need some ner and er dataset

**Comment by kaharjan** [comment]
Thank you for attention of our paper. It is our pleasure to share resources with you. Unfortunately, there is some copyright issues on the corpus. So we withdrew our corpus. We are working on to releasing it again, and hope it would be released as soon as possible. However, we are not able to promise you the exact time.

**Comment by AngledLuffa** [comment]
Hey, I was wondering, has there been any progress in making the data public again?  Thanks!
